version: "3.3"

services:
  serve:
    image: node:18
    volumes: &default-volumes
      - ./:/src:ro
      - ./node_modules:/src/node_modules
      - ./yarn.lock:/src/yarn.lock
    ports:
      - 8080:8080
    stop_signal: SIGKILL
    command:
    - sh
    - -c
    - cd /src &&
      yarn &&
      yarn run start

  build:
    image: node:18
    volumes: *default-volumes
    command:
    - sh
    - -c
    - cd /src &&
      yarn &&
      yarn run build

  gameserver:
    image: node:18
    volumes: *default-volumes
    ports:
      - 8081:80
    command:
    - sh
    - -c
    - cd /src &&
      node_modules/.bin/ts-node src/multiplayer/server.ts

  texture-packer:
    image: openjdk:11
    volumes:
      - ./raw_assets:/src:ro
      - ./assets:/trg
      - texture_packer_tmp:/app
    command:
    - /bin/bash
    - -c
    - echo 'Starting texture packer';
      if [ ! -f /app/runnable-texturepacker.jar ]; then curl -L 'https://libgdx.badlogicgames.com/nightlies/runnables/runnable-texturepacker.jar' > /app/runnable-texturepacker.jar; fi;
      while true; do
        CURRENT_HASH=`ls /src | xargs "-I{}" md5sum "/src/{}" | md5sum`;
        if [ "$${CURRENT_HASH}" != "$${PREV_HASH}" ]; then
          java -jar /app/runnable-texturepacker.jar /src /trg;
          PREV_HASH="$${CURRENT_HASH}";
        fi;
        sleep 1;
      done;



volumes:
  texture_packer_tmp:
